name: Android build CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with: 
          java-version: 1.8
      - name: Build with gradle
        uses: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        
  
